# Verified FireRed build targets.
# These values are derived from the eight audited retail baselines.

TARGET ?= us_rev0
VALID_TARGETS := jp_rev0 jp_rev1 us_rev0 us_rev1 fr de it es

ifeq ($(filter $(TARGET),$(VALID_TARGETS)),)
  $(error Unknown TARGET '$(TARGET)'; expected one of: $(VALID_TARGETS))
endif

# Defaults overridden below.
TITLE := POKEMON FIRE
MAKER_CODE := 01
GAME_VERSION := FIRERED
FEATURE_PRINT_INIT := 0
FEATURE_FLASH_MEMORY_GUARD := 0
FEATURE_ASSERTS_ENABLED := 0

ifeq ($(TARGET),jp_rev0)
  GAME_CODE := BPRJ
  GAME_LANGUAGE := JAPANESE
  GAME_REVISION := 0
  GF_LANGUAGE := 1
  GFX_DATA_ADDRESS := 0x08C00000
  FEATURE_PRINT_INIT := 1
  FEATURE_ASSERTS_ENABLED := 1
endif

ifeq ($(TARGET),jp_rev1)
  GAME_CODE := BPRJ
  GAME_LANGUAGE := JAPANESE
  GAME_REVISION := 1
  GF_LANGUAGE := 1
  GFX_DATA_ADDRESS := 0x08C00000
endif

ifeq ($(TARGET),us_rev0)
  GAME_CODE := BPRE
  GAME_LANGUAGE := ENGLISH
  GAME_REVISION := 0
  GF_LANGUAGE := 2
  GFX_DATA_ADDRESS := 0x08D00000
  FEATURE_PRINT_INIT := 1
  FEATURE_ASSERTS_ENABLED := 1
endif

ifeq ($(TARGET),us_rev1)
  GAME_CODE := BPRE
  GAME_LANGUAGE := ENGLISH
  GAME_REVISION := 1
  GF_LANGUAGE := 2
  GFX_DATA_ADDRESS := 0x08D00000
  FEATURE_PRINT_INIT := 1
  FEATURE_FLASH_MEMORY_GUARD := 1
  FEATURE_ASSERTS_ENABLED := 1
endif

ifeq ($(TARGET),fr)
  GAME_CODE := BPRF
  GAME_LANGUAGE := FRENCH
  GAME_REVISION := 0
  GF_LANGUAGE := 3
  GFX_DATA_ADDRESS := 0x08D00000
endif

ifeq ($(TARGET),it)
  GAME_CODE := BPRI
  GAME_LANGUAGE := ITALIAN
  GAME_REVISION := 0
  GF_LANGUAGE := 4
  GFX_DATA_ADDRESS := 0x08D00000
  FEATURE_FLASH_MEMORY_GUARD := 1
endif

ifeq ($(TARGET),de)
  GAME_CODE := BPRD
  GAME_LANGUAGE := GERMAN
  GAME_REVISION := 0
  GF_LANGUAGE := 5
  GFX_DATA_ADDRESS := 0x08D00000
  FEATURE_FLASH_MEMORY_GUARD := 1
endif

ifeq ($(TARGET),es)
  GAME_CODE := BPRS
  GAME_LANGUAGE := SPANISH
  GAME_REVISION := 0
  GF_LANGUAGE := 7
  GFX_DATA_ADDRESS := 0x08D00000
endif

CPPFLAGS += -DFIRERED_TARGET_$(shell echo $(TARGET) | tr a-z A-Z)=1
CPPFLAGS += -DFEATURE_PRINT_INIT=$(FEATURE_PRINT_INIT)
CPPFLAGS += -DFEATURE_FLASH_MEMORY_GUARD=$(FEATURE_FLASH_MEMORY_GUARD)
CPPFLAGS += -DFEATURE_ASSERTS_ENABLED=$(FEATURE_ASSERTS_ENABLED)
CPPFLAGS += -DGF_LANGUAGE=$(GF_LANGUAGE)

# The allocator's AGB_ASSERT_EX paths are present only in the verified
# assert-enabled family.  Keep this explicit rather than deriving NDEBUG from
# software revision.
ifeq ($(FEATURE_ASSERTS_ENABLED),0)
  CPPFLAGS += -DNDEBUG
endif
